Dataingestion:
  root_path : artifacts
  file_path : E:\Study\Machine learning\GitCodes\HousingML\DataSet\housing.csv
  row_data_path : artifacts/data_ingestion/row_data.csv
  train_data_path : artifacts/data_ingestion/train.csv
  test_data_path : artifacts/data_ingestion/test.csv

DataTransformation:
  preprocessor_path : artifacts/data_transformation/preprocessor.pkl

Modeltrainer :
  model_path : artifacts/model_path/model.pkl
  preprocessor_path : artifacts/data_transformation/preprocessor.pkl
  train_data_path : artifacts/data_ingestion/train.csv

ModelEvaluation :
  model_path : artifacts/model_path/model.pkl
  preprocessor_path : artifacts/data_transformation/preprocessor.pkl
  test_data_path : artifacts/data_ingestion/test.csv

ModelPrediction :
  model_path : artifacts/model_path/model.pkl
  preprocessor_path : artifacts/data_transformation/preprocessor.pkl